import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const {data,isLoading} = trpc.hello.useQuery({text: "satish"})

  if (isLoading) return <p>Loading...</p>

  return (
    <div className="h-screen w-screen flex flex-col justify-center items-center">
      <Head>
        <title>T3 stack</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-2xl">Which Pokemon is rounded</div>
      <div className="p-3"></div>
      <div className="border rounded p-8 flex justify-between items-center max-w-2xl">
        <div className="h-16 w-16 bg-pink-300"></div>
        <div className="p-8">VS</div>
        <div className="h-16 w-16 bg-pink-300"></div>
      </div>
      {data?.greeting}
    </div>
  );
};

export default Home;
